version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped

  web:
    container_name: web
    build:
      context: .
    restart: unless-stopped
    entrypoint: './wait-for-it.sh -t 60 mongodb:27017 -- /run.sh'
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
